name: KidGigawatt
favicon: null
layout_spectrum: 0.66567
typography_spectrum: 0.54861
title: Joyriding in Autismland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2fbe6'
    - '#abd571'
    - '#535b68'
    - '#040406'
    - '#a2a4a0'
  brandStrength: 0.6966601028107107
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
