name: KidGigawatt
favicon: null
layout_spectrum: 0.7787755278404802
typography_spectrum: 0.42192049976438284
title: Joyriding in Autismland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ff01'
    - '#b2c3d4'
    - '#20202c'
    - '#ffffff'
    - '#489d01'
  brandStrength: 0.6966601028107107
  lightness: 0.09944398724474013
  saturation: 0.28930147690698504
  rhythmicContrast: 0.2491521134506911
purpose: []
